name: Zowe CLI Coverage

on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      upload-results:
        type: boolean
        description: Upload coverage results
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - run: npm ci

    - run: node index.js

    - uses: actions/upload-artifact@v2
      with:
        name: 'results'
        path: 'results/*.csv'

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.event_name == 'schedule' || inputs.upload-results == true }}
      with:
        commit_author: GitHub Actions <actions@github.com>
        commit_message: 'Upload coverage results'
        file_pattern: '*.csv'
