name: Zowe CLI Coverage

on:
  schedule:
  - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - run: npm ci

    - run: node index.js

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Upload coverage results'
        file_pattern: '*.csv'
